
```{r setup}
library(compr)
library(tidyverse)
library(broom)
```

```{r}
#nba_game<-load("data/nba_game.rda")
comp_mod <- comp_glm(home_winner ~ 1, data = nba_game,
                     p1 = "home", p2 = "away",
                     #p1_effects = ~ point_server1,
                     #p2_effects = ~ point_server2,
                     ref_player = "Houston Rockets"
                     )

```

```{r}
coefficients <- comp_mod$coefficients
# this is the bump for the home team
coefficients <- coefficients[-1]

coefficients <- coefficients[1:8]
names <- names(coefficients)

win_probability <- function(player, coefficients, reference_player) {
  #linear_combination <- coefficients[player] - coefficients[reference_player]
  win_probability <- 1 / (1 + exp(-coefficients[player]))
  return(win_probability)
}

df <- data.frame(Name = character(0), Prob = numeric(0))

for (name in names) {
  prob <- win_probability(name, coefficients, reference_player)
  new_row <- data.frame(Name = name, Prob = round(prob * 100, 2))
  df <- rbind(df, new_row)
}
rownames(df) <- NULL

#fct_reorder
df$Name <- reorder(df$Name, -df$Prob)

ggplot(df, aes(x = Name, y = Prob)) +
  geom_segment(aes(xend = Name, yend = 0)) +
  geom_point(size =3) +
  labs(title = "Lolipop of Win Probability Against the Boston Celtics", x = "Team Name", y = "Win Probability (%)") +
  theme_bw()
```


```{r}
#trying to put it into a function
comp_mod$data$ref_player

lolipop_prob <- function(model){
    coefficients <- model$coefficients
    coefficients <- coefficients[-1]
    names <- names(coefficients)
  
  win_probability <- function(player, coefficients, reference_player) {
    #linear_combination <- coefficients[player] - coefficients[reference_player]
    win_probability <- 1 / (1 + exp(coefficients[player]))
    return(win_probability)
  }
  
  df <- data.frame(Name = character(0), Prob = numeric(0))
  
  for (name in names) {
    prob <- win_probability(name, coefficients, reference_player)
    new_row <- data.frame(Name = name, Prob = round(prob * 100, 2))
    df <- rbind(df, new_row)
  }
  rownames(df) <- NULL
  

df <- df %>%
  arrange(desc(Prob)) %>%
  mutate(Name = fct_reorder(Name, -Prob))
  
  ggplot(df, aes(x = Name, y = Prob)) +
    geom_segment(aes(xend = Name, yend = 0)) +
    geom_point(size =3) +
    labs(title = paste("Lollipop of the", comp_mod$data$ref_player,"Win Probability"), x = "Name", y = "Win Probability (%)") +
    theme_bw() +
    coord_flip()
    
}
```


```{r}
lolipop_prob(comp_mod)

#make a function with model as argument 
augment_test <- augment(comp_mod)

t <- augment(comp_mod) %>% 
  mutate(pct_prob = 100 * plogis(.fitted)) %>% 
  #relocate(diabetes, .fitted, pct_prob) %>% 
  arrange(-.fitted)
```





















```{r}
loli_teams <- data.frame(
  comp_mod[["data"]][["players_unique"]],
  rep(comp_mod[["data"]][["ref_player"]], 30)
)

fitted_df <- data.frame(
                   comp_mod[["data"]][["player1_vec"]],
                   comp_mod[["data"]][["player2_vec"]],
                   comp_mod[["fitted.values"]]
                   )

aug_fitted_df <- augment(
  comp_mod,
  #data = nba_game,
  newdata = loli_teams,
  se_fit = TRUE,
  interval = 'prediction'
  #FIXME do I want to use prediction?
)
```



```{r}
augmented_data <- augment(comp_mod, data = combined_df)

win_probabilities <- 1 / (1 + exp(-augmented_data$.fitted))

df <- data.frame(
  Prob = round(win_probabilities * 100, 2),
  Fitted = augmented_data$.fitted,
  Team = combined_df$away,
  Residuals = augmented_data$.resid,  
  Hat = augmented_data$.hat,  
  Sigma = augmented_data$.sigma,  
  CooksD = augmented_data$.cooksd,  
  StdResiduals = augmented_data$.std.resid  
)

df <- df %>%
group_by(Team) %>%
summarize(Avg_Prob = mean(Prob),
          SE_Fitted = sd(Fitted) / sqrt(n()))

df <- df %>%
  arrange(desc(Avg_Prob)) %>%
  mutate(Team = fct_reorder(Team, -Avg_Prob))

# Convert "Team" to a factor and reorder it as needed
df$Team <- factor(df$Team, levels = unique(df$Team))

# Create a ggplot with horizontal error bars using geom_segment
ggplot(df, aes(x = Avg_Prob, y = Team)) +
  geom_point(size = 2) +
  geom_segment(aes(xend = Avg_Prob - SE_Fitted, yend = Team, x = Avg_Prob)) +
  geom_segment(aes(xend = Avg_Prob + SE_Fitted, yend = Team, x = Avg_Prob)) +
  theme_bw()

win_probabilities <- augment(comp_mod, type.predict = "response", se_fit = TRUE)
head(win_probabilities)

```


## rep("celtics, 31)




