---
title: "lollipop_plot_a"
author: "James Wolpe"
date: "2023-09-25"
output: html_document
---
```{r}
library(tidyverse)
library(broom)
```

```{r}
nba_game
comp_mod <- comp_glm(home_winner ~ 1, data = nba_game,
                     p1 = "home", p2 = "away",
                     #p1_effects = ~ point_server1,
                     #p2_effects = ~ point_server2,
                     ref_player = "Houston Rockets"
                     )

opp_player_list <- comp_mod[["data"]][["players_unique"]]
ref_player_list <- rep(comp_mod[["data"]][["ref_player"]], 30)
```

```{r}

fitted_df <- data.frame(
                   home = comp_mod[["data"]][["player1_vec"]],
                   away = comp_mod[["data"]][["player2_vec"]],
                   win_perc = comp_mod[["fitted.values"]]
                   )

aug_fitted_df <- augment(
  comp_mod,
  data = nba_game,
  newdata = fitted_df,
  se_fit = TRUE,
  type.predict = "link"
  #FIXME do I want to use prediction?
)

loli_players <- data.frame(
  home = rep(comp_mod[["data"]][["ref_player"]], 30),
  away = comp_mod[["data"]][["players_unique"]]

) %>% filter(home !=away)

joined_df <- left_join(loli_players, distinct(aug_fitted_df),  by = c("home", "away"))

joined_df_1 <- joined_df %>% 
  mutate( 
    se = .05
  #se = .se.fit
  #se= 1 / (1 + exp(joined_df$.se.fit))
  #se= .se.fit/.fitted
  )

```


```{r}
ggplot(joined_df_1, aes(x = away, y = win_perc)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = win_perc - se, ymax = win_perc + se))+
  theme_bw()+
  coord_flip()
```





```{r}

plot_win_perc_with_error_bars <- function(model, data, player_of_interest) {
  opp_player_list <- model[["data"]][["players_unique"]]
  ref_player_list <- rep(model[["data"]][[player_of_interest]], 30)
  
  fitted_df <- data.frame(
    home = model[["data"]][["player1_vec"]],
    away = model[["data"]][["player2_vec"]]
  )
  
  aug_fitted_df <- augment(
    model,
    data = data,
    newdata = fitted_df,
    se_fit = TRUE,
    #FIXME if it defaults to this do I even need to include it
    type.predict = "link"
  )
  
  loli_players <- data.frame(
    home = rep(player_of_interest, 30),
    away = model[["data"]][["players_unique"]]
  ) %>% filter(home != away)
  
  joined_df <- left_join(loli_players, distinct(aug_fitted_df), by = c("home", "away"))
  
  joined_df_1 <- joined_df %>% 
    mutate( 
      se = 0.05
    ) %>%
    mutate(away = fct_reorder(away, win_perc))
  
  ggplot(joined_df_1, aes(x = away, y = win_perc)) +
    geom_point(size = 2) +
    geom_errorbar(aes(ymin = win_perc - se, ymax = win_perc + se)) +
    labs(x = "Player",
         y = "Win Percentage",
         title = paste(player_of_interest, "Plot"))+
    scale_y_continuous(labels = scales::percent_format(scale = 100))+
    theme_bw() +
    coord_flip()
}

plot_win_perc_with_error_bars(comp_mod, nba_game, 'Boston Celtics')
```


```{r}
plot_win_perc_with_error_bars <- function(model, data, player_of_interest){
  #player_of_interest <- 'Boston Celtics'
  #data <- nba_game
  
  opp_player_list <- comp_mod[["data"]][["players_unique"]]
  ref_player_list <- rep(comp_mod[["data"]][[player_of_interest]], 30)
  
  fitted_df <- data.frame(
    p1 = comp_mod[["data"]][["player1_vec"]],
    p2 = comp_mod[["data"]][["player2_vec"]]
  )
  
  aug_fitted_df <- augment(
    comp_mod,
    data = data,
    newdata = fitted_df,
    se_fit = TRUE,
    #FIXME if it defaults to this do I even need to include it
    type.predict = "link"
  )
  
  loli_players <- data.frame(
    p1 = rep(player_of_interest, 30),
    p2 = comp_mod[["data"]][["players_unique"]]
  ) %>% filter(p1 != p2)
  
  joined_df <- left_join(loli_players, distinct(aug_fitted_df), by = c("p1", "p2"))
  
  joined_df_1 <- joined_df %>% 
    mutate( 
      win_perc = exp(.fitted)/ (1+exp(.fitted)),
      u_bound = exp(.fitted + .se.fit)/ (1+ exp(.fitted + .se.fit)),
      l_bound = exp(.fitted - .se.fit)/ (1+ exp(.fitted - .se.fit))
    ) %>%
    mutate(p2 = fct_reorder(p2, win_perc))
  
  ggplot(joined_df_1, aes(x = p2, y = win_perc)) +
    geom_point(size = 2) +
    geom_errorbar(aes(ymin = l_bound, ymax = u_bound)) +
    labs(x = "Player",
         y = "Win Percentage",
         title = paste(player_of_interest, "Plot"))+
    scale_y_continuous(labels = scales::percent_format(scale = 100))+
    theme_bw() +
    coord_flip()
}
```


```{r}
win_pred <- function(model, data, player_of_interest){
  #a f
  
  
}
```

