---
title: "Untitled"
author: "James Wolpe"
date: "2023-09-13"
output: html_document
---

```{r}
library(rvest)

# Define the list of URLs
urls <- c(
  "https://www.basketball-reference.com/leagues/NBA_2023_games.html",
  "https://www.basketball-reference.com/leagues/NBA_2023_games-november.html",
  "https://www.basketball-reference.com/leagues/NBA_2023_games-december.html",
  "https://www.basketball-reference.com/leagues/NBA_2023_games-january.html",
  "https://www.basketball-reference.com/leagues/NBA_2023_games-february.html",
  "https://www.basketball-reference.com/leagues/NBA_2023_games-march.html",
  "https://www.basketball-reference.com/leagues/NBA_2023_games-april.html"
  
)

# Initialize an empty list to store DataFrames
dfs <- list()

# Loop through the URLs and scrape data
for (url in urls) {
  page_html <- url %>%
    read_html()
  
  df <- page_html %>%
    html_nodes("table") %>%
    .[[1]] %>%
    html_table(header = TRUE)
  
  dfs[[url]] <- df
}

# Combine the DataFrames into one
nba_game <- do.call(rbind, dfs)
rownames(nba_game) <- NULL
```


```{r}
nba_game <- nba_game[1:1230, ]
nba_game <- nba_game[, -c(2, 7, 9, 10, 11)]

nba_game <- nba_game %>%
  rename(
    date = 1,       
    away = 2,       
    away_pts = 3,   
    home = 4,       
    home_pts = 5,   
    OT = 6          
  )

nba_game <- nba_game %>% #there are both OT and 2OT
  mutate(OT = ifelse(OT == "", FALSE, TRUE),
         home_winner = ifelse(home_pts > away_pts, TRUE, FALSE))

saveRDS(nba_game, file = "data/nba_game.rda")
```


